"""cuestionario_invitaciones table

Revision ID: 23ea4bec8b0b
Revises: 66a75aa4007a
Create Date: 2026-10-01 13:11:51.175629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23ea4bec8b0b'
down_revision: Union[str, Sequence[str], None] = '66a75aa4007a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuestionario_invitaciones',
    sa.Column('caso_id', sa.UUID(), nullable=False),
    sa.Column('contacto_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.Enum('ENVIADA', 'ABIERTA', 'RESPONDIDA', 'ANULADA', name='invitacion_estado'), nullable=False),
    sa.Column('expira_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('abierta_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('respondida_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('borrador', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.ForeignKeyConstraint(['contacto_id'], ['contactos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_cuestionario_invitaciones_caso_id'), 'cuestionario_invitaciones', ['caso_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cuestionario_invitaciones_caso_id'), table_name='cuestionario_invitaciones')
    op.drop_table('cuestionario_invitaciones')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS invitacion_estado')
