"""catalog tables (dominios, preguntas)

Revision ID: 2ae5014435b4
Revises: 759a92cb4405
Create Date: 2026-09-22 13:32:23.730421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae5014435b4'
down_revision: Union[str, Sequence[str], None] = '759a92cb4405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dominios',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('peso', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('total_preguntas', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_dominios_codigo'), 'dominios', ['codigo'], unique=True)
    op.create_table('preguntas',
    sa.Column('dominio_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.SmallInteger(), nullable=False),
    sa.Column('texto_es', sa.Text(), nullable=False),
    sa.Column('texto_en', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('CONTROL', 'RIESGO', name='pregunta_tipo'), nullable=False),
    sa.Column('polaridad', sa.Enum('POSITIVA', 'NEGATIVA', name='polaridad'), nullable=False),
    sa.Column('tier', sa.Enum('CRITICO', 'ALTO', 'ESTANDAR', name='tier'), nullable=False),
    sa.Column('multiplicador', sa.SmallInteger(), nullable=False),
    sa.Column('impacto_primario', sa.String(length=200), nullable=True),
    sa.Column('referencias_regulatorias', sa.Text(), nullable=True),
    sa.Column('justificacion_tier', sa.Text(), nullable=True),
    sa.Column('explicacion_control_es', sa.Text(), nullable=True),
    sa.Column('explicacion_control_en', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dominio_id', 'numero', name='uq_pregunta_dominio_numero')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preguntas')
    op.drop_index(op.f('ix_dominios_codigo'), table_name='dominios')
    op.drop_table('dominios')
    # ### end Alembic commands ###
