"""caso_documentos table + instrucciones IA en caso_respuestas

Revision ID: 598b29cff1c6
Revises: c0b875a999b5
Create Date: 2026-09-22 17:24:01.545174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598b29cff1c6'
down_revision: Union[str, Sequence[str], None] = 'c0b875a999b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caso_documentos',
    sa.Column('caso_id', sa.UUID(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=False),
    sa.Column('clasificacion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('caso_respuestas', sa.Column('instrucciones_respuesta_es', sa.Text(), nullable=True))
    op.add_column('caso_respuestas', sa.Column('instrucciones_respuesta_en', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caso_respuestas', 'instrucciones_respuesta_en')
    op.drop_column('caso_respuestas', 'instrucciones_respuesta_es')
    op.drop_table('caso_documentos')
    # ### end Alembic commands ###
