"""casos and contactos tables

Revision ID: 92537474542a
Revises: 2ae5014435b4
Create Date: 2026-09-22 13:49:33.451229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92537474542a'
down_revision: Union[str, Sequence[str], None] = '2ae5014435b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casos',
    sa.Column('gdld', sa.String(length=100), nullable=True),
    sa.Column('empresa_responsable', sa.String(length=200), nullable=False),
    sa.Column('nombre_proyecto', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('CANDIDATO', 'INGRESADO', 'HERRAMIENTA_TERCERO', name='caso_tipo'), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'EN_ANALISIS', 'ESPERANDO_PROVEEDOR', 'CERRADO_APROBADO', 'RECHAZADO', name='caso_estado'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactos',
    sa.Column('caso_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('rol', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contactos')
    op.drop_table('casos')
    # ### end Alembic commands ###
