"""caso_preguntas and caso_respuestas tables

Revision ID: c0b875a999b5
Revises: 92537474542a
Create Date: 2026-09-22 13:53:46.175507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b875a999b5'
down_revision: Union[str, Sequence[str], None] = '92537474542a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caso_preguntas',
    sa.Column('caso_id', sa.UUID(), nullable=False),
    sa.Column('pregunta_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caso_id', 'pregunta_id', name='uq_caso_pregunta')
    )
    op.create_table('caso_respuestas',
    sa.Column('caso_pregunta_id', sa.UUID(), nullable=False),
    sa.Column('respuesta', sa.Enum('SI', 'NO', 'NA_ARQ', 'NA_FASE', 'PENDIENTE', name='respuesta_valor'), nullable=False),
    sa.Column('control_compensatorio', sa.Text(), nullable=True),
    sa.Column('factor_mitigacion_pct', sa.SmallInteger(), nullable=True),
    sa.Column('owner_responsable', sa.String(length=200), nullable=True),
    sa.Column('accion_remediacion', sa.Text(), nullable=True),
    sa.Column('fecha_objetivo', sa.Date(), nullable=True),
    sa.Column('evidencia_esperada', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['caso_pregunta_id'], ['caso_preguntas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caso_pregunta_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caso_respuestas')
    op.drop_table('caso_preguntas')
    # ### end Alembic commands ###
