"""cuestionario_invitaciones idioma

Revision ID: ece0f83e9af2
Revises: 23ea4bec8b0b
Create Date: 2026-10-01 18:02:33.281956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece0f83e9af2'
down_revision: Union[str, Sequence[str], None] = '23ea4bec8b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Las invitaciones existentes quedan en español (el server_default).
    idioma = sa.Enum('ES', 'EN', name='idioma')
    idioma.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuestionario_invitaciones', sa.Column('idioma', idioma, server_default='ES', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuestionario_invitaciones', 'idioma')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS idioma')
